name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: Install dependencies
      run: dotnet restore Xam.Forms.GraceAlert/Xam.Forms.GraceAlert/Xam.Forms.GraceAlert.csproj
      
    - name: Build and Pack
      run: dotnet pack Xam.Forms.GraceAlert/Xam.Forms.GraceAlert/Xam.Forms.GraceAlert.csproj -p:NuspecFile=../Nuspecs/Xam.Forms.GraceAlert.nuspec --configuration Release --no-restore
    
    - name: Publish NuGet
      uses: rohith/publish-nuget@v2.3.0
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: Xam.Forms.GraceAlert/Xam.Forms.GraceAlert/Xam.Forms.GraceAlert.csproj
        PACKAGE_NAME: Xam.Forms.GraceAlert_del
        VERSION_STATIC: 0.0.99
        # Flag to enable / disable git tagging
        TAG_COMMIT: false
        NUGET_KEY: ${{ secrets.NUGET_KEY }}

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: xam.forms.gracealert
        # Directory containing files to upload
        path: Xam.Forms.GraceAlert/Xam.Forms.GraceAlert/bin/Release
